### ISSUE TITLE
paramiko.ssh_exception.SSHException: Error connecting via ssh: 'HPE3PARSSHClient' object has no attribute 'san_privatekey'

### ISSUE THREAD

**Issue by cchib** [hpe-storage/python-3parclient#21]
root@hLinux:/3parpython# cat hpe3par.py
import logging
import os
import paramiko
from random import randint
import time
import re
from eventlet import greenthread
from hpe3parclient import client, exceptions, http, ssh

sshclient = ssh.HPE3PARSSHClient(ip="x.x.x.x", login="user", password=None,port=22,conn_timeout=None,privatekey='/home/nfvadmin/.ssh/id_rsa')
sshclient.open()
#, port=22, conn_timeout=None, privatekey=None)
output = sshclient._ssh_execute('showvv')
print "Output s",output
#ssh.open()
#time.sleep(30)
#print "ssh session started"
sshclient.close()
#print "ssh session closed"

Error :
root@hLinux:/3parpython# python hpe3par.py
No handlers could be found for logger "hpe3parclient.ssh"
Traceback (most recent call last):
  File "hpe3par.py", line 38, in <module>
    sshclient.open()
  File "/usr/local/lib/python2.7/dist-packages/hpe3parclient/ssh.py", line 140, in open
    raise paramiko.SSHException(msg)
paramiko.ssh_exception.SSHException: Error connecting via ssh: 'HPE3PARSSHClient' object has no attribute 'san_privatekey'

**Comment by wdurairaj** [comment]
Fixed. Please confirm and close
